
#Background image
background {
    monitor = 
    path = ~/Pictures/Wallpaper/moeve.png
    blur_passes = 2
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# Profile image
image {
    # monitor =
    monitor = eDP-1
    path = ~/Pictures/User/shadow/ProfilePicture100x100.jpeg
    border_size = 2
    border_color = rgba(255, 0, 255, 1)
    size = 160
    rounding = -1
    position = 0, 40
    halign = center
    valign = center
}

# Date isplay
label {
    monitor = 
    text = cmd[update:1000] echo -e "$(LC_TIME=en_US.UTF-8 date +"%A, %B %d")"
    color = rgba(216, 222, 233, 0.90)
    font_size = 25
    font_family = SF Pro Display Semibold
    position = 0, 350
    halign = center
    valign = center
}

# Time display
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba(216, 222, 233, 0.90)
    font_size = 120
    font_family = SF Pro Display Bold
    position = 0, 230
    halign = center
    valign = center
}

# Input field
input-field {
    monitor =
    #monitor = eDP-1
    size = 280, 55
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    font_family = SF Pro Display Bold
    placeholder_text = <i><span foreground="##ffffff99">Enter Password</span></i>
    hide_input = false
    position = 0, -210
    halign = center
    valign = center
}
