### Monitors ###
#Use "hyprctl monitors" to list all monitors available

env = WLR_DRM_DEVICES,/dev/dri/card1

#monitor = eDP-1, disable
#monitor = DP-1, disable
#monitor = HDMI-A-1, disable 


#eDisplayport 1 -- Internal Monitor
monitorv2 {
output = eDP-1
mode = preferred
position = 0x0
scale = 1
transform = 0
}
#Displayport 1 -- USB-C Monitor out
monitorv2 {
output = DP-1
mode = preferred
position = auto
scale = 2
transform = 0
#mirror = eDP-1

}

#HDMI 1
monitorv2 {
output = HDMI-A-1
mode = preferred
position = auto
scale = 1.5
transform = 0
}



workspace = 1, monitor:DP-2
